### ISSUE TITLE
'browse Videos' is broken

### ISSUE THREAD

**Issue by kylegillen** [BalestraPatrick/RealmVideo#4] opened 2016-05-08 12:06 UTC
Hi:

Great app idea. Thanks for open sourcing it.

The 'browse videos' button seems to break the app on an iPhone 6s. It works correctly in the simulator, but on a physical device - no luck.

The issue seems to be when `BrowseVideosViewController` tries to load videos within the `init` function:

`videos = RealmParser().videos`

Eventually, the app crashes with the following error:

`fatal error: unexpectedly found nil while unwrapping an Optional value`
# 

iPhone 6s
iOS 9.3.1
Xcode 7.3.1

**Comment by BalestraPatrick** [comment] 2016-05-08 12:39
Hey, thanks for the bug report! 
Unfortunately I can't reproduce the issue on my iPhone 6s Plus. Are you able to track down the line of the crash?

**Comment by kylegillen** [comment] 2016-05-08 12:56
Thanks for enquiring. The crash happens at line 21 of `RealmParser.swift`.
Looks like `posts` is `nil` when you try to force-unwrap it.

![image](https://cloud.githubusercontent.com/assets/711457/15097919/2397e1b8-1503-11e6-8c80-7e683e1dd654.png)

**Comment by BalestraPatrick** [comment] 2016-05-08 13:11
I was able to reproduce the crash if the iPhone doesn't have internet connection or it's slow. Is that possible?

**Comment by kylegillen** [comment] 2016-05-08 13:15
You're right on the money!

I was connected to a distant network which seems to be what was causing the issue.

Thanks for the help.

**Comment by BalestraPatrick** [comment] 2016-05-08 13:34
Bug fixed with commit 0240284a. If you are offline, this message will be shown 👍 
![img_2154](https://cloud.githubusercontent.com/assets/3658887/15098073/5ec96700-1532-11e6-936d-f6c08f149616.PNG)

**Closed as completed by BalestraPatrick** 2016-05-08 13:34 UTC
